### ISSUE TITLE
pragma cannot be set when runtime is automatic

### ISSUE THREAD

**Issue by stahlmanDesign** [kylejlin/react-isometric-projection#1]
In trying to get your demo to work, in NextJS (I haven't tested Regular React) there is an error related to this part of the code:
```
// The comment below tells the transpiler to use jsxToObj()
//   instead of React.createElement() when transpiling JSX to function calls

/** @jsx jsxToObj **/
```

> pragma cannot be set when runtime is automatic`

If I remove the commented lines there is a different error:
> TypeError: vbd is undefined

**Comment by kylejlin** [comment]
> pragma cannot be set when runtime is automatic

I'm not familiar with NextJS, but I'm guessing this error message means the compiler/transpiler won't let you use the `@jsx` directive, probably due to the current NextJS configuration. In that case, you'll have to either give up on using react-isometric-projection's JSX syntax (you can usual the [standard `Polygon({...})` syntax](https://github.com/kylejlin/react-isometric-projection/blob/master/docs/meshLib.md) instead) or you'll have to change your build configuration to allow the use of the `@jsx` directive.

**Comment by kylejlin** [comment]
Closing, as this issue does not seem to be a problem with react-isometric-projection, but rather with the NextJS config. If I'm wrong, feel free to reopen.
